## New Linux Inputs - Updated 02 April 2025

## Monitor

[monitor:///etc/modprobe.d/*.conf]
disabled = 0
sourcetype = modprobe.d
index = nix

[monitor:///var/log/auth.log]
disabled = 0
index = nix
source = /var/log/auth.log
sourcetype = auth_log

[monitor:///var/log/audit/audit.log]
disabled = 0
index = nix
source = /var/log/audit/audit.log
sourcetype = audit_log

[monitor:///var/log/apt/history.log*]
disabled = 0
index = nix
source = /var/log/apt/history.log
sourcetype = history_log

[monitor:///var/log/dmesg]
disabled = 0
index = nix
source = /var/log/dmesg
sourcetype = dmesg

[monitor:///var/log/ufw.log]
disabled = 0
index = nix
source = /var/log/ufw.log
sourcetype = ufw_log

[monitor:///var/log/clamav/clamav.log*]
disabled = 0
index = nix
source = /var/log/clamav/clamav.log
sourcetype = clamav_log

## Scripts

[script:///opt/splunkforwarder/etc/apps/linux_deployment_app/bin/lsblk.sh]
index = nix
sourcetype = _json
source = Script:lsblk.sh
interval = 86400
disabled = 0

[script:///opt/splunkforwarder/etc/apps/linux_deployment_app/bin/dpkg-query.sh]
index = nix
sourcetype = _json
source = Script:dpkg-query.sh
interval = 604800
disabled = 0

[script:///opt/splunkforwarder/etc/apps/linux_deployment_app/bin/version.sh]
index = nix
sourcetype = _json
source = Script:version.sh
interval = 604800
disabled = 0

[script:///opt/splunkforwarder/etc/apps/linux_deployment_app/bin/os-release.sh]
index = nix
sourcetype = _json
source = Script:os-release.sh
interval = 604800
disabled = 0

[script:///opt/splunkforwarder/etc/apps/linux_deployment_app/bin/df_storage_space.sh]
index = nix
sourcetype = _json
source = Script:df_storage_space.sh
interval = 3600
disabled = 0

[script:///opt/splunkforwarder/etc/apps/linux_deployment_app/bin/clamav_defs.sh]
index = nix
sourcetype = _json
source = Script:clamav_defs.sh
interval = 86400
disabled = 0

[script:///opt/splunkforwarder/etc/apps/linux_deployment_app/bin/clamscan_info.sh]
index = nix
sourcetype = _json
source = Script:clamscan_info.sh
interval = 86400
disabled = 0

[script://./bin/hardware.sh]
index = nix
sourcetype = hardware
source = Script:hardware.sh
interval = 86400
disabled = 0

# Lists users who could login (i.e., they are assigned a login shell)
[script://./bin/usersWithLoginPrivs.sh]
index = nix
sourcetype = usersWithLoginPrivs
source = Script:usersWithLoginPrivs.sh
interval = 86400
disabled = 0

[script://./bin/passwd.sh]
disabled = 0
index = nix
interval = 86400
source = Script:passwd.sh
sourcetype = UserAccounts

# New script to check if /etc/modprobe.d/DISASTIG.conf 
# install usb-storage /bin/false
# blacklist usb-storage
[script://./bin/usb_block.sh]
disabled = 0
index = nix
interval = 86400
source = Script:usb_block.sh
sourcetype = usb_block

[script://./bin/lastlog.sh]
index = nix
sourcetype = last_log
source = Script:lastlog.sh
interval = 86400
disabled = 0

# This script checks the last reported system shutdown and reboot
[script://./bin/last.sh]
index = nix
sourcetype = last
source = Script:last.sh
interval = 86400
disabled = 0

[script://./bin/update.sh]
disabled = 0
index = nix
sourcetype = update
source = Script:update.sh
interval = 86400