#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 0
label = Linux

[launcher]
author = Nick Nelson
description = This app is only intended for the Splunk server and helps parse/tag events ingested from Linux-based Splunk forwarders.
version = 1.0.0

