[default]
enableDataIntegrityControl = true

maxTotalDataSizeMB = 90000

### Volume Definitions ###
# By default, $SPLUNK_DB = %SPLUNK_HOME%\var\lib\splunk #

[volume:internal_primary]
path = $SPLUNK_DB
maxVolumeDataSizeMB = 15000

[volume:internal_secondary]
path = $SPLUNK_DB
maxVolumeDataSizeMB = 30000

[volume:primary]
path = $SPLUNK_DB
maxVolumeDataSizeMB = 150000

[volume:secondary]
path = $SPLUNK_DB
maxVolumeDataSizeMB = 300000

### Built-In Indexes ###

[_audit]
homePath = volume:internal_primary\audit\db
coldPath = volume:internal_secondary\audit\colddb
thawedPath = $SPLUNK_DB\audit\thaweddb

[_internal]
homePath = volume:internal_primary\_internaldb\db
coldPath = volume:internal_secondary\_internaldb\colddb
thawedPath = $SPLUNK_DB\_internaldb\thaweddb

[_thefishbucket]
homePath = volume:internal_primary\fishbucket\db
coldPath = volume:internal_secondary\fishbucket\colddb
thawedPath = $SPLUNK_DB\fishbucket\thaweddb

[history]
homePath = volume:internal_primary\historydb\db
coldPath = volume:internal_secondary\historydb\colddb
thawedPath = $SPLUNK_DB\historydb\thaweddb

[main]
homePath = volume:internal_primary\defaultdb\db
coldPath = volume:internal_secondary\defaultdb\colddb
thawedPath = $SPLUNK_DB\defaultdb\thaweddb

[summary]
homePath = volume:internal_primary\summarydb\db
coldPath = volume:internal_secondary\summarydb\colddb
thawedPath = $SPLUNK_DB\summarydb\thaweddb

### Custom Indexes ###

# Can hold switch/router syslog and ASA Firewall logs if applicable #
[cisco]
homePath = volume:primary\cisco\db
coldPath = volume:secondary\cisco\colddb
thawedPath = $SPLUNK_DB\cisco\thaweddb

# can include RSA logs and other mfa log sources (ex: SurePass) #
[mfa]
homePath = volume:primary\mfa\db
coldPath = volume:secondary\mfa\colddb
thawedPath = $SPLUNK_DB\mfa\thaweddb

# Linux logs and scripted inputs
[nix]
homePath = volume:primary\nix\db
coldPath = volume:secondary\nix\colddb
thawedPath = $SPLUNK_DB\nix\thaweddb

[palo-alto]
homePath = volume:primary\palo-alto\db
coldPath = volume:secondary\palo-alto\colddb
thawedPath = $SPLUNK_DB\palo-alto\thaweddb

# Configure rsyslog to send to Splunk server on 1475/TCP
[proxmox]
homePath = volume:primary\proxmox\db
coldPath = volume:secondary\proxmox\colddb
thawedPath = $SPLUNK_DB\proxmox\thaweddb

# For any remaining CD-burning logs that may exist
[roxio]
homePath = volume:primary\roxio\db
coldPath = volume:secondary\roxio\colddb
thawedPath = $SPLUNK_DB\roxio\thaweddb

# windows holds scripted inputs and custom file monitoring #
[windows]
homePath = volume:primary\windows\db
coldPath = volume:secondary\windows\colddb
thawedPath = $SPLUNK_DB\windows\thaweddb

# winevents holds event logs saved in the winevt folder #
[winevents]
homePath = volume:primary\winevents\db
coldPath = volume:secondary\winevents\colddb
thawedPath = $SPLUNK_DB\winevents\thaweddb

[vmware]
homePath = volume:primary\vmware\db
homePath.maxDataSizeMB = 10000
coldPath = volume:secondary\vmware\colddb
coldPath.maxDataSizeMB = 25000
thawedPath = $SPLUNK_DB\vmware\thaweddb