
[splunktcp://9997]
disabled = 0

[SSL]
serverCert = $SPLUNK_HOME\etc\auth\mycerts\combinedServerCert.pem
sslPassword = $7$Zs6cWHxErPgwBSPJGF5hSXR3tMoAvsUy0DLkzN8KejlXSrV/SJwNEgg=
sslVersions = tls1.2

[script://$SPLUNK_HOME\bin\scripts\splunk-wmi.path]
disabled = 0

