[netapp]
KV_MODE = xml
BREAK_ONLY_BEFORE = ^\s*<Event>
MUST_BREAK_AFTER = (</Event\b)
SHOULD_LINEMERGE = true
TIME_PREFIX = (<TimeCreated)
pulldown_type = 1
EXTRACT-EventName = ^(?:[^>\n]*>){6}(?P<EventName>[^<]+)
EXTRACT-Result = ^(?:[^/\n]*/){8}\w+><\w+>(?P<Result>[^<]+)
EXTRACT-TargetUserName = ^(?:[^=\n]*=){7}"\w+">(?P<TargetUserName>\w+)
EXTRACT-Computer = ^<\w+><\w+><\w+\s+\w+="\w+\-\w+\-\w+"/><\w+>\d+</\w+><\w+>\w+\s+\w+</\w+><\w+>\d+\.\d+</\w+><\w+>\w+</\w+><\w+>\d+</\w+><\w+>\d+</\w+><\w+>\d+\w+\d+</\w+><\w+>\w+\s+\w+</\w+><\w+\s+\w+="\d+\-\d+\-\d+\w+\d+:\d+:\d+\.\d+\w+"/><\w+/><\w+>\w+</\w+><\w+>(?P<Computer>[^<]+)
EXTRACT-IPVersion4 = ^(?:[^"\n]*"){8}>(?P<IPVersion4>[^<]+)
EXTRACT-EventID = ^[^/\n]*/><\w+>(?P<EventID>\d+)

[auditd]
SHOULD_LINEMERGE = True
MUST_BREAK_AFTER = ----
NO_BINARY_CHECK = true
SEDCMD-remove = s/(?m)----//g
disabled = 0



