#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 0
label = Network Infrastructure

[launcher]
author = Nick Nelson
description = Used to monitor networking switches, firewalls, and systems that send syslog
version = 1.0.0

