# Edited 5/2/2025 -Nick

# Cisco switches
[tcp://1470]
connection_host = dns
index = cisco
sourcetype = cisco:ios
disabled = 0

# VSphere
[tcp://1471]
connection_host = dns
index = vmware
sourcetype = vm:vsphere

# Vcenter
[tcp://1472]
connection_host = dns
index = vmware
sourcetype = vm:vcenter

# Palo Alto Firewalls
[tcp://1473]
connection_host = dns
index = cisco
sourcetype = palo-alto

# ESXi
[tcp://1474]
connection_host = dns
index = vmware
sourcetype = vm:esxi

# ProxMox
[tcp://1475]
connection_host = dns
index = proxmox
sourcetype = vm:proxmox