# Updated 5/21/2025

[system_logs]
EXTRACT-RealUser = ^(?:[^ \n]* ){5}(?P<RealUser>[^:]+)

[syslog]
EXTRACT-Cisco_Denied = (?i)^(?:[^ ]* ){9}(?P<FIELDNAME>[^ ]+)

[source::...Audit_report*]
sourcetype = audit_report

[reduced-too_small]
EXTRACT-HeaderToken = (?i)header,+(?P<TypeID>[^,]+)+,+(?P<ver>[^,])+,+(?P<type>[^,]+)
EXTRACT-SubjectToken = (?i)subject,+(?P<auid>[^,]+)+,+(?P<uid>[^,]+)+,+(?P<gid>[^,]+)+,+(?P<ruid>[^,]+)+,+(?P<rgid>[^,]+)+,+(?P<pid>[^,]+)+,+(?P<sid>[^,]+)+,+(?P<terminal>[^,]+)
EXTRACT-ReturnToken = (?i)return,+(?P<res>[^,]+)
EXTRACT-TextToken = (?i)text,+(?P<op>[^,]+)
EXTRACT-PathToken = (?i)path,+(?P<path>[^,]+)
EXTRACT-Target_id = ^(?:[^\.\n]*\.){3}\d+,\w+,(?P<Target_id>\w+)

[software]
NO_BINARY_CHECK = true
SHOULD_LINEMERGE = false
category = Custom
description = software
pulldown_type = true

[Audit_report_S.DODDEVSOL-too_small]
EXTRACT-Nixacct = ^[^\.\n]*\.\d+\s+(?P<Nixacct>\w+)


[netapp]
EXTRACT-FailureReason = ^<\w+><\w+><\w+\s+\w+="\w+\-\w+\-\w+"/><\w+>\d+</\w+><\w+>\w+\s+\w+</\w+><\w+>\d+\.\d+</\w+><\w+>\w+</\w+><\w+>\d+</\w+><\w+>\d+</\w+><\w+>\d+\w+\d+</\w+><\w+>\w+\s+\w+</\w+><\w+\s+\w+="\d+\-\d+\-\d+\w+\d+:\d+:\d+\.\d+\w+"/><\w+/><\w+>\w+</\w+><\w+>[a-f0-9]+\-\d+\-[a-f0-9]+\-[a-f0-9]+\-[a-f0-9]+/[a-f0-9]+\-\d+\-[a-f0-9]+\-\d+\-[a-f0-9]+</\w+><\w+/></\w+><\w+><\w+\s+\w+="\w+"\s+\w+="\d+">\d+\.\d+\.\d+\.\d+</\w+><\w+\s+\w+="\w+">\d+</\w+><\w+\s+\w+="\w+">\w+\-\d+\-\d+\-\d+</\w+><\w+\s+\w+="\w+">\w+</\w+><\w+\s+\w+="\w+">\w+</\w+><\w+\s+\w+="\w+">\d+\w+\d+\w+\d+</\w+><\w+\s+\w+="\w+">%%\d+</\w+><\w+\s+\w+="\w+">(?P<FailureReason>[^<]+)
EXTRACT-FailureReasonString = ^<\w+><\w+><\w+\s+\w+="\w+\-\w+\-\w+"/><\w+>\d+</\w+><\w+>\w+\s+\w+</\w+><\w+>\d+\.\d+</\w+><\w+>\w+</\w+><\w+>\d+</\w+><\w+>\d+</\w+><\w+>\d+\w+\d+</\w+><\w+>\w+\s+\w+</\w+><\w+\s+\w+="\d+\-\d+\-\d+\w+\d+:\d+:\d+\.\d+\w+"/><\w+/><\w+>\w+</\w+><\w+>[a-f0-9]+\-\d+\-[a-f0-9]+\-[a-f0-9]+\-[a-f0-9]+/[a-f0-9]+\-\d+\-[a-f0-9]+\-\d+\-[a-f0-9]+</\w+><\w+/></\w+><\w+><\w+\s+\w+="\w+"\s+\w+="\d+">\d+\.\d+\.\d+\.\d+</\w+><\w+\s+\w+="\w+">\d+</\w+><\w+\s+\w+="\w+">\w+\-\d+\-\d+\-\d+</\w+><\w+\s+\w+="\w+">\w+</\w+><\w+\s+\w+="\w+">\w+\d+\-\w+</\w+><\w+\s+\w+="\w+">\d+\w+\d+</\w+><\w+\s+\w+="\w+">%%\d+</\w+><\w+\s+\w+="\w+">(?P<FailureReasonString>[^<]+)

[auth-too_small]

[service]
LOOKUP-ServiceToBeDisabled_auto = ServiceToBeDisabled Service AS app OUTPUTNEW Description AS Description Service AS Service Severity AS Severity

[config_check]
NO_BINARY_CHECK = true
LINE_BREAKER = ([\r\n]+)
SHOULD_LINEMERGE = false
disabled = false

[cisco:ios]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
SHOULD_LINEMERGE = true
category = Custom
disabled = false
pulldown_type = true

[software]
BREAK_ONLY_BEFORE_DATE = 
LINE_BREAKER = ([\r\n]+)
description = software
disabled = false

[SEP_AV_Date]
DATETIME_CONFIG =
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
pulldown_type = true

[time]
DATETIME_CONFIG =
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
disabled = false
pulldown_type = true
