
[getent]
filename = getent.csv

[SecRelObj]
filename = SecRelObj.csv

[PrivCommands_desc]
filename = PrivCommands_desc.csv

[ServiceToBeDisabled]
filename = services_disabled.csv
#match_type = WILDCARD(app) WILDCARD(Service)

[nix_hosts_lookup]
fields_list = hostname,sourceHost,os

[nix_hosts_alive]
batch_index_query = 0
case_sensitive_match = 1
filename = nix_hosts_alive.csv

[audit_rules_rh7]
batch_index_query = 0
case_sensitive_match = 1
default_match = unknown
filename = audit_rules_rh7.csv
min_matches = 1

