[source::WinEventLog:Security]
EVAL-action = case(EventCode=="4663" AND like(Accesses, "%ReadData%"), "read", EventCode=="4663" AND like(Accesses, "%ReadEA%"), "read", EventCode=="4663" AND like(Accesses, "%READ_CONTROL%"), "read", EventCode=="4663" AND like(Accesses, "%READ_CONTROL%"), "read", EventCode=="4663" AND like(Accesses, "%ReadAttributes%"), "read", EventCode=="4663" AND like(Accesses, "%WriteData%"), "modified", EventCode=="4663" AND like(Accesses, "%WriteAttributes%"), "modified", EventCode=="4663" AND like(Accesses, "%WriteEA%"), "modified", EventCode=="4663" AND like(Accesses, "%WRITE_DAC%"), "granted", EventCode=="4663" AND like(Accesses, "%WriteEA%"), "modified", EventCode=="4663" AND like(Accesses, "%AppendData%"), "modified", EventCode=="4663" AND like(Accesses, "%WRITE_OWNER%"), "granted", EventCode=="4663" AND like(Accesses, "%DELETE%"), "delete")

##### Explanation for SEDCMD Extractions #####
## clean_info_text_from_winsystem_events_this_event: This will delete all the infomation text at the end of event starting from "This event is generated..." before indexing


##### SEDCMD Extractions #####
[source::WinEventLog:System]
SEDCMD-clean_info_text_from_winsystem_events_this_event = s/This [Ee]vent is generated[\S\s\r\n]+$//g

##### Explanation for SEDCMD Extractions #####
## windows_security_event_formater: This will replace all values like "Account Name:-" to "Account Name:"
## windows_security_event_formater_null_sid_id: This will replace all values like "Security ID:NULL SID" to "Security ID:" and all values like "Logon ID:0x0" to "Logon ID:"
## cleansrcip: This will replace all values like "Source Network Address: ::1" or "Source Network Address:127.0.0.1" to "Source Network Address:"
## cleansrcport: This will replace all values like "Source Port:0" to "Source Port:"
## remove_ffff: This will replace all values like "Client Address: ::ffff:10.x.x.x" to "Client Address:10.x.x.x" which Addresses most of the Ipv6 log event issues
## clean_info_text_from_winsecurity_events_certificate_information: This will delete all the infomation text at the end of event starting from "Certificate information is..." before indexing
## clean_info_text_from_winsecurity_events_token_elevation_type: This will delete all the infomation text at the end of event starting from "Token Elevation Type indicates..." before indexing
## clean_info_text_from_winsecurity_events_this_event: This will delete all the infomation text at the end of event starting from "This event is generated..." before indexing
## cleanxmlsrcport: This will replace all values like <Data Name='IpPort'>0<\/Data> to <Data Name='IpPort'><\/Data> in XmlWinEventLog:Security
## cleanxmlsrcip: This will replace all values like <Data Name='IpAddress'>::1<\/Data> or <Data Name='IpAddress'>127.0.0.1<\/Data> to <Data Name='IpAddress'><\/Data> in XmlWinEventLog:Security


##### SEDCMD Extractions #####
[source::WinEventLog:Security]
SEDCMD-windows_security_event_formater = s/(?m)(^\s+[^:]+\:)\s+-?$/\1/g
SEDCMD-windows_security_event_formater_null_sid_id = s/(?m)(:)(\s+NULL SID)$/\1/g s/(?m)(ID:)(\s+0x0)$/\1/g
SEDCMD-cleansrcip = s/(Source Network Address:\s*(\:\:1|127\.0\.0\.1))/Source Network Address:/
SEDCMD-cleansrcport = s/(Source Port:\s*0)/Source Port:/
SEDCMD-remove_ffff = s/::ffff://g
SEDCMD-clean_info_text_from_winsecurity_events_certificate_information = s/Certificate information is only[\S\s\r\n]+$//g
SEDCMD-clean_info_text_from_winsecurity_events_token_elevation_type = s/Token Elevation Type indicates[\S\s\r\n]+$//g
SEDCMD-clean_info_text_from_winsecurity_events_this_event = s/This [Ee]vent is generated[\S\s\r\n]+$//g

[WinEventLog:System]
EXTRACT-LumFileName = ^\d+/\d+/\d+\s+\d+:\d+:\d+\s+\w+\s+\w+=\w+\s+\w+=\w+\s+\w+=\d+\s+\w+=\d+\s+\w+=\w+\s+\w+=\w+\d+\.\w+\.\w+\s+\w+=\w+\s+\w+=\w+\s+\w+=\d+\s+\w+=\w+\s+\w+=\w+\s+\w+\s+\w+\s+\w+\s+"(?P<FileName>[^"]+)