[audit_log]
TRANSFORMS-set = setnull,setparsing

[_json]
DATETIME_CONFIG = CURRENT

[source::Script:clamav_defs.sh]
DATETIME_CONFIG = CURRENT

[source::Script:clamscan_info.sh]
DATETIME_CONFIG = CURRENT

[history_log]
EXTRACT-start_date = (?m)Start-Date:\s*(?P<start_date>\d+\-\d+\-\d+\s+\d+:\d+:\d+)
EXTRACT-commandline = (?m)Commandline:\s*(?P<commandline>.*?)(?=\s*Remove:|\s*Install:|\s*Requested-By:|\s*End-Date:|$)
EXTRACT-install = (?m)Install:\s*(?P<install>.*?)(?=\s*Upgrade:|\s*Error:|\s*Requested-By:|\s*End-Date:|$)
EXTRACT-requested_by = (?m)Requested-By:\s*(?P<requested_by>.*?)(?=\s*Install:|\s*Upgrade:|\s*Error:|\s*Remove:|\s*End-Date:|$)
EXTRACT-remove = (?m)Remove:\s*(?P<remove>.*?)(?=\s*Upgrade:|\s*Install:|\s*Requested-By:|\s*End-Date:|\s*Error:|$)

[source::/var/log/sudo.log]
EXTRACT-CMD = ^\w*\s*.*COMMAND=(?P<CMD>.*)

[linux_secure]
EXTRACT-SessionStatus = (?i)^(?:[^:]*:){5}\s+\w+\s+(?P<SessionStatus>[^ ]+)
EXTRACT-SessionType = (?i) pam_unix\((?P<SessionType>[^:]+)
EXTRACT-SessionUser = (?i) user (?P<SessionUser>[^ ]+)

[clamav]
EXTRACT-AVDate = (?i)^(?:[^/]*/){2}(?P<AVDate>[^/]+)
EXTRACT-Version = (?i)^(?P<Version>[^/]+)

[auditd]
EXTRACT-Nix_user_clogin = ^[^'\n]*'\w+=(?P<Nix_user_clogin>\w+\s+)
EXTRACT-audit_status = ^(?:[^ \n]* ){4}(?P<audit_status>[^,]+)
EXTRACT-Linux_msg = (?:msg='op=)(?P<Linux_msg>.+?(?=exe))
LOOKUP-PrivCommands_desc_linux_auditd_auto = PrivCommands_desc full_path AS exe OUTPUTNEW command AS "Privileged Command" description AS Description

[authlog]
EXTRACT-Nix_user = ^[^=\n]*=(?P<Nix_user>\w+)
EXTRACT-Nix_user2 = ^[^'\n]*'(?P<Nix_user2>[^']+)
EXTRACT-Nix_user_failure,Nix_login_failure = ^[^'\n]*'(?P<Nix_user_failure>\w+)[^:\n]*:\s+(?P<Nix_login_failure>.+)
EXTRACT-Nix_failure_status2 = ^(?:[^:\n]*:){5}\s+(?P<Nix_failure_status2>[\w+\s+]+[\r\n]+)
EXTRACT-Nix_failure_reason = ^(?:[^=\n]*=){9}(?P<Nix_failure_reason>.+)

[aide]
DATETIME_CONFIG = 
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
category = Custom
description = Security files that were added, removed and changed
pulldown_type = true
