[setnull]
REGEX = .
DEST_KEY = queue
FORMAT = nullQueue

[setparsing]
REGEX = (type=USER_CMD|type=EXECVE|type=CRED_ACQ|type=CRED_DISP|type=CRED_DISP|type=USER_AUTH|type=USER_LOGIN|type=USER_ACCT|type=USER_MGMT|type=CONFIG_CHANGE|type=SERVICE_START|type=SERVICE_STOP|type=CWD|type=SYSCALL)
DEST_KEY = queue
FORMAT = indexQueue